
/*
Code generated with Faust version 2.40.12
Compilation options: -lang wasm-ib -cn sound -es 1 -mcd 16 -single -ftz 2 
*/

function getJSONsound() {
	return '{"name": "sound","filename": "sound.dsp","version": "2.40.12","compile_options": "-lang wasm-ib -cn sound -es 1 -mcd 16 -single -ftz 2","include_pathnames": ["/usr/local/share/faust","/usr/local/share/faust","/usr/share/faust",".","/tmp/sessions/BFB4FDB4597D7C38CFF16B34AA16B48E5FA2DF7B/web/wasmjs-worklet"],"size": 1155740,"inputs": 0,"outputs": 2,"meta": [ { "basics_lib_name": "Faust Basic Element Library" },{ "basics_lib_version": "0.8" },{ "compile_options": "-single -scal -I libraries/ -I project/ -lang wasm" },{ "delays_lib_name": "Faust Delay Library" },{ "delays_lib_version": "0.1" },{ "demos_lib_name": "Faust Demos Library" },{ "demos_lib_version": "0.1" },{ "demos_lib_zita_light_author": "Julius O. Smith III" },{ "demos_lib_zita_light_licence": "MIT" },{ "envelopes_lib_ar_author": "Yann Orlarey, Stéphane Letz" },{ "envelopes_lib_author": "GRAME" },{ "envelopes_lib_copyright": "GRAME" },{ "envelopes_lib_license": "LGPL with exception" },{ "envelopes_lib_name": "Faust Envelope Library" },{ "envelopes_lib_version": "0.2" },{ "filename": "sound.dsp" },{ "filters_lib_allpass_comb_author": "Julius O. Smith III" },{ "filters_lib_allpass_comb_copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>" },{ "filters_lib_allpass_comb_license": "MIT-style STK-4.3 license" },{ "filters_lib_fir_author": "Julius O. Smith III" },{ "filters_lib_fir_copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>" },{ "filters_lib_fir_license": "MIT-style STK-4.3 license" },{ "filters_lib_iir_author": "Julius O. Smith III" },{ "filters_lib_iir_copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>" },{ "filters_lib_iir_license": "MIT-style STK-4.3 license" },{ "filters_lib_lowpass0_highpass1": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>" },{ "filters_lib_lowpass0_highpass1_author": "Julius O. Smith III" },{ "filters_lib_lowpass_author": "Julius O. Smith III" },{ "filters_lib_lowpass_copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>" },{ "filters_lib_lowpass_license": "MIT-style STK-4.3 license" },{ "filters_lib_name": "Faust Filters Library" },{ "filters_lib_peak_eq_rm_author": "Julius O. Smith III" },{ "filters_lib_peak_eq_rm_copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>" },{ "filters_lib_peak_eq_rm_license": "MIT-style STK-4.3 license" },{ "filters_lib_resonlp_author": "Julius O. Smith III" },{ "filters_lib_resonlp_copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>" },{ "filters_lib_resonlp_license": "MIT-style STK-4.3 license" },{ "filters_lib_tf1_author": "Julius O. Smith III" },{ "filters_lib_tf1_copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>" },{ "filters_lib_tf1_license": "MIT-style STK-4.3 license" },{ "filters_lib_tf1s_author": "Julius O. Smith III" },{ "filters_lib_tf1s_copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>" },{ "filters_lib_tf1s_license": "MIT-style STK-4.3 license" },{ "filters_lib_tf2_author": "Julius O. Smith III" },{ "filters_lib_tf2_copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>" },{ "filters_lib_tf2_license": "MIT-style STK-4.3 license" },{ "filters_lib_tf2s_author": "Julius O. Smith III" },{ "filters_lib_tf2s_copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>" },{ "filters_lib_tf2s_license": "MIT-style STK-4.3 license" },{ "filters_lib_version": "0.3" },{ "library_path0": "/libraries/stdfaust.lib" },{ "library_path1": "/libraries/oscillators.lib" },{ "library_path10": "/libraries/signals.lib" },{ "library_path11": "/libraries/routes.lib" },{ "library_path2": "/libraries/platform.lib" },{ "library_path3": "/libraries/maths.lib" },{ "library_path4": "/libraries/basics.lib" },{ "library_path5": "/libraries/envelopes.lib" },{ "library_path6": "/libraries/filters.lib" },{ "library_path7": "/libraries/demos.lib" },{ "library_path8": "/libraries/reverbs.lib" },{ "library_path9": "/libraries/delays.lib" },{ "maths_lib_author": "GRAME" },{ "maths_lib_copyright": "GRAME" },{ "maths_lib_license": "LGPL with exception" },{ "maths_lib_name": "Faust Math Library" },{ "maths_lib_version": "2.5" },{ "name": "sound" },{ "oscillators_lib_name": "Faust Oscillator Library" },{ "oscillators_lib_version": "0.3" },{ "platform_lib_name": "Generic Platform Library" },{ "platform_lib_version": "0.2" },{ "reverbs_lib_name": "Faust Reverb Library" },{ "reverbs_lib_version": "0.2" },{ "routes_lib_hadamard_author": "Remy Muller, revised by Romain Michon" },{ "routes_lib_name": "Faust Signal Routing Library" },{ "routes_lib_version": "0.2" },{ "signals_lib_name": "Faust Signal Routing Library" },{ "signals_lib_version": "0.3" },{ "version": "2.44.5" }],"ui": [ {"type": "vgroup","label": "sound","items": [ {"type": "hgroup","label": "Zita Light","items": [ {"type": "vslider","label": "Dry/Wet Mix","shortname": "Wet_Mix","address": "/sound/Zita_Light/Dry/Wet_Mix","index": 262180,"meta": [{ "1": "" },{ "style": "knob" },{ "tooltip": "-1 = dry, 1 = wet" }],"init": 0,"min": -1,"max": 1,"step": 0.01},{"type": "vslider","label": "Level","shortname": "Level","address": "/sound/Zita_Light/Level","index": 262156,"meta": [{ "2": "" },{ "style": "knob" },{ "tooltip": "Output scale         factor" },{ "unit": "dB" }],"init": -6,"min": -70,"max": 40,"step": 0.1}]},{"type": "hslider","label": "freq","shortname": "freq","address": "/sound/freq","index": 262196,"init": 440,"min": 20,"max": 24000,"step": 1},{"type": "hslider","label": "gain","shortname": "gain","address": "/sound/gain","index": 262176,"init": 0.4,"min": 0,"max": 1,"step": 0.01},{"type": "button","label": "gate","shortname": "gate","address": "/sound/gate","index": 262224}]}]}';
}
function getBase64Codesound() { return "AGFzbQEAAAAB5YCAgAATYAJ/fwBgBH9/f38AYAF9AX1gAX0BfWABfwF/YAF/AX9gAn9/AX1gAX8Bf2ACf38AYAF/AGACf38AYAJ/fwBgAX8AYAJ/fwF/YAJ/fwF/YAJ9fQF9YAN/f30AYAF9AX1gAX0BfQK9gICAAAUDZW52BV9jb3NmAAIDZW52BV9leHBmAAMDZW52BV9wb3dmAA8DZW52BV9zaW5mABEDZW52BV90YW5mABIDj4CAgAAOAAEEBQYHCAkKCwwNDhAFjICAgAABAaCAgIAAiIiAgAAHuoGAgAAMB2NvbXB1dGUABgxnZXROdW1JbnB1dHMABw1nZXROdW1PdXRwdXRzAAgNZ2V0UGFyYW1WYWx1ZQAJDWdldFNhbXBsZVJhdGUACgRpbml0AAsNaW5zdGFuY2VDbGVhcgAMEWluc3RhbmNlQ29uc3RhbnRzAA0MaW5zdGFuY2VJbml0AA4aaW5zdGFuY2VSZXNldFVzZXJJbnRlcmZhY2UADw1zZXRQYXJhbVZhbHVlABIGbWVtb3J5AgAKzPCAgAAO4YGAgAABA39BACEEQQAhAkEAIQNBACECA0ACQEGMxcYAIAJBAnRqQQA2AgAgAkEBaiECIAJBAkgEQAwCDAELCwtBACEDA0ACQEGUxcYAIANBAnRqQQA2AgAgA0EBaiEDIANBAkgEQAwCDAELCwtBACEEA0ACQEEAQQE2AozFRkEAQQAoApDFRkEAKAKYxUZqQYCABG82ApTFRiAEQQJ0Q9sPyThBACgClMVGspQQAzgCAEEAQQAoAozFRjYCkMVGQQBBACgClMVGNgKYxUYgBEEBaiEEIARBgIAESARADAIMAQsLCwujtYCAAAIEf2h9QQAhBEEAIQVDAAAAACEIQwAAAAAhCUMAAAAAIQpDAAAAACELQwAAAAAhDEMAAAAAIQ1DAAAAACEOQwAAAAAhD0MAAAAAIRBBACEGQwAAAAAhEUMAAAAAIRJDAAAAACETQwAAAAAhFEMAAAAAIRVBACEHQwAAAAAhFkMAAAAAIRdDAAAAACEYQwAAAAAhGUMAAAAAIRpDAAAAACEbQwAAAAAhHEMAAAAAIR1DAAAAACEeQwAAAAAhH0MAAAAAISBDAAAAACEhQwAAAAAhIkMAAAAAISNDAAAAACEkQwAAAAAhJUMAAAAAISZDAAAAACEnQwAAAAAhKEMAAAAAISlDAAAAACEqQwAAAAAhK0MAAAAAISxDAAAAACEtQwAAAAAhLkMAAAAAIS9DAAAAACEwQwAAAAAhMUMAAAAAITJDAAAAACEzQwAAAAAhNEMAAAAAITVDAAAAACE2QwAAAAAhN0MAAAAAIThDAAAAACE5QwAAAAAhOkMAAAAAITtDAAAAACE8QwAAAAAhPUMAAAAAIT5DAAAAACE/QwAAAAAhQEMAAAAAIUFDAAAAACFCQwAAAAAhQ0MAAAAAIURDAAAAACFFQwAAAAAhRkMAAAAAIUdDAAAAACFIQwAAAAAhSUMAAAAAIUpDAAAAACFLQwAAAAAhTEMAAAAAIU1DAAAAACFOQwAAAAAhT0MAAAAAIVBDAAAAACFRQwAAAAAhUkMAAAAAIVNDAAAAACFUQwAAAAAhVUMAAAAAIVZDAAAAACFXQwAAAAAhWEMAAAAAIVlDAAAAACFaQwAAAAAhW0MAAAAAIVxDAAAAACFdQwAAAAAhXkMAAAAAIV9DAAAAACFgQwAAAAAhYUMAAAAAIWJDAAAAACFjQwAAAAAhZEMAAAAAIWVDAAAAACFmQwAAAAAhZ0MAAAAAIWhDAAAAACFpQwAAAAAhakMAAAAAIWtDAAAAACFsQwAAAAAhbUMAAAAAIW5DAAAAACFvIANBAGooAgAhBCADQQRqKAIAIQVBACoCiIAQQwAAIEFDzcxMPUEAKgKMgBCUEAKUIQhBACoCnIAQQQAqAqCAEJQhCUEAKgKIgBBBACoCpIAQlCEKQQAqArSAECELQQAqArCAECALlCEMQwAAADRDAAAAPyALlIuXIQ1BACoCsIAQIA2UIQ5DAACAP0EAKgKEgBAgDZWTIQ9BACoC0IAQIRBBACEGA0ACQCAIQQAqApCAEEEAKgKYgBCUkiERQQAgEbxBgICA/AdxBH0gEQVDAAAAAAs4ApSAECAKQQAqApCAEEEAKgKsgBCUkiESQQAgErxBgICA/AdxBH0gEgVDAAAAAAs4AqiAEEEAKgKogBBDAACAP5IhEyAMQQAqAryAECAMQQAqAryAEJKOk5IhFEEAIBS8QYCAgPwHcQR9IBQFQwAAAAALOAK4gBAgDkEAKgLEgBBDAACAv5KSIRUgFUMAAAAAXSEHIA5BACoCxIAQkiEWIAcEfSAWBSAVCyEXQQAgF7xBgICA/AdxBH0gFwVDAAAAAAs4AsCAECAOQQAqAsSAECAPIBWUkpIhGCAHBH0gFgUgGAshGSAZvEGAgID8B3EEfSAZBUMAAAAACyEaQQAgEDgC1IAQQQBBACgC4IAQQQAoAuCAEEEASmogEEEAKgLYgBBfbCAQQQAqAtiAEF5qNgLcgBBBACgC3IAQsiEbQwAAgEdBACoCuIAQlKhBAnQqAgBDAAAAQCAalEMAAIC/kpRDAAAAAEEAKgLMgBAgG5RBACoC5IAQQQAqAsiAECAbk5RDAACAP5KWl5RBACoCnIAQQQAqAuiAEEEAKgL4gBCUQQAqAuyAEEEAKgL0gBCUkpSTIRxBACAcvEGAgID8B3EEfSAcBUMAAAAACzgC8IAQQQAqAviAEEEAKgLwgBBDAAAAQEEAKgL0gBCUkpIhHSAJIBMgHZSUIR5DAACAP0MAAAA/IBOUkyEfQwAAAABBACoCjIEQQQAqApCBEEEAKgKYgRCUQQAqAszERkEAKgLQxEaSk5STISBBACAgvEGAgID8B3EEfSAgBUMAAAAACzgClIEQQQAqAoSBEEEAKgLMxEZBACoCiIEQQQAqApSBEJSSlEEAKgKcgRBBACoCpIEQlJIhIUEAICG8QYCAgPwHcQR9ICEFQwAAAAALOAKggRBBrIEQQQAoAqiBEEH//wFxQQJ0akPzBLU+QQAqAqCBEJRDCOU8HpI4AgBBsIEYQQAoAqiBEEH//wBxQQJ0aiAJIB2UOAIAQ5qZmT5BsIEYQQAoAqiBEEEAKAKwgRxrQf//AHFBAnRqKgIAlCEiQ5qZGT9BACoCvMEclEGsgRBBACgCqIEQQQAoAqyBGGtB//8BcUECdGoqAgCSICKTISNBtIEcQQAoAqiBEEH/D3FBAnRqICM4AgBBtIEcQQAoAqiBEEEAKAK0wRxrQf8PcUECdGoqAgAhJEEAICS8QYCAgPwHcQR9ICQFQwAAAAALOAK4wRxDAAAAAEOamRk/ICOUkyElICW8QYCAgPwHcQR9ICUFQwAAAAALISZDAAAAAEEAKgKMgRBBACoCkIEQQQAqAszBHJRBACoCnMRGQQAqAqDERpKTlJMhJ0EAICe8QYCAgPwHcQR9ICcFQwAAAAALOALIwRxBACoCwMEcQQAqApzERkEAKgLEwRxBACoCyMEclJKUQQAqAtDBHEEAKgLYwRyUkiEoQQAgKLxBgICA/AdxBH0gKAVDAAAAAAs4AtTBHEHcwRxBACgCqIEQQf//AXFBAnRqQ/MEtT5BACoC1MEclEMI5TwekjgCAEOamRk/QQAqAujBJZRB3MEcQQAoAqiBEEEAKALcwSRrQf//AXFBAnRqKgIAkiAikyEpQeDBJEEAKAKogRBB/x9xQQJ0aiApOAIAQeDBJEEAKAKogRBBACgC4MEla0H/H3FBAnRqKgIAISpBACAqvEGAgID8B3EEfSAqBUMAAAAACzgC5MElQwAAAABDmpkZPyAplJMhKyArvEGAgID8B3EEfSArBUMAAAAACyEsQwAAAABBACoCjIEQQQAqApCBEEEAKgL4wSWUQQAqArTERkEAKgK4xEaSk5STIS1BACAtvEGAgID8B3EEfSAtBUMAAAAACzgC9MElQQAqAuzBJUEAKgK0xEZBACoC8MElQQAqAvTBJZSSlEEAKgL8wSVBACoChMIllJIhLkEAIC68QYCAgPwHcQR9IC4FQwAAAAALOAKAwiVBiMIlQQAoAqiBEEH//wBxQQJ0akPzBLU+QQAqAoDCJZRDCOU8HpI4AgBBiMIlQQAoAqiBEEEAKAKIwilrQf//AHFBAnRqKgIAICJDmpkZP0EAKgKUwiqUkpIhL0GMwilBACgCqIEQQf8fcUECdGogLzgCAEGMwilBACgCqIEQQQAoAozCKmtB/x9xQQJ0aioCACEwQQAgMLxBgICA/AdxBH0gMAVDAAAAAAs4ApDCKkMAAAAAQ5qZGT8gL5STITEgMbxBgICA/AdxBH0gMQVDAAAAAAshMkMAAAAAQQAqAoyBEEEAKgKQgRBBACoCpMIqlEEAKgKExEZBACoCiMRGkpOUkyEzQQAgM7xBgICA/AdxBH0gMwVDAAAAAAs4AqDCKkEAKgKYwipBACoChMRGQQAqApzCKkEAKgKgwiqUkpRBACoCqMIqQQAqArDCKpSSITRBACA0vEGAgID8B3EEfSA0BUMAAAAACzgCrMIqQbTCKkEAKAKogRBB//8BcUECdGpD8wS1PkEAKgKswiqUQwjlPB6SOAIAQbTCKkEAKAKogRBBACgCtMIya0H//wFxQQJ0aioCACAiQ5qZGT9BACoCwMIzlJKSITVBuMIyQQAoAqiBEEH/H3FBAnRqIDU4AgBBuMIyQQAoAqiBEEEAKAK4wjNrQf8fcUECdGoqAgAhNkEAIDa8QYCAgPwHcQR9IDYFQwAAAAALOAK8wjNDAAAAAEOamRk/IDWUkyE3IDe8QYCAgPwHcQR9IDcFQwAAAAALIThDAAAAAEEAKgKMgRBBACoCkIEQQQAqAtDCM5RBACoCwMRGQQAqAsTERpKTlJMhOUEAIDm8QYCAgPwHcQR9IDkFQwAAAAALOALMwjNBACoCxMIzQQAqAsDERkEAKgLIwjNBACoCzMIzlJKUQQAqAtTCM0EAKgLcwjOUkiE6QQAgOrxBgICA/AdxBH0gOgVDAAAAAAs4AtjCM0HgwjNBACgCqIEQQf//AHFBAnRqQ/MEtT5BACoC2MIzlEMI5TwekjgCAEHgwjNBACgCqIEQQQAoAuDCN2tB//8AcUECdGoqAgAgIkOamRk/QQAqAuyCOJSSkyE7QeTCN0EAKAKogRBB/w9xQQJ0aiA7OAIAQeTCN0EAKAKogRBBACgC5II4a0H/D3FBAnRqKgIAITxBACA8vEGAgID8B3EEfSA8BUMAAAAACzgC6II4Q5qZGT8gO5QhPSA9vEGAgID8B3EEfSA9BUMAAAAACyE+QwAAAABBACoCjIEQQQAqApCBEEEAKgL8gjiUQQAqApDERkEAKgKUxEaSk5STIT9BACA/vEGAgID8B3EEfSA/BUMAAAAACzgC+II4QQAqAvCCOEEAKgKQxEZBACoC9II4QQAqAviCOJSSlEEAKgKAgzhBACoCiIM4lJIhQEEAIEC8QYCAgPwHcQR9IEAFQwAAAAALOAKEgzhBjIM4QQAoAqiBEEH//wBxQQJ0akPzBLU+QQAqAoSDOJRDCOU8HpI4AgBBjIM4QQAoAqiBEEEAKAKMgzxrQf//AHFBAnRqKgIAICJDmpkZP0EAKgKYgz2UkpMhQUGQgzxBACgCqIEQQf8fcUECdGogQTgCAEGQgzxBACgCqIEQQQAoApCDPWtB/x9xQQJ0aioCACFCQQAgQrxBgICA/AdxBH0gQgVDAAAAAAs4ApSDPUOamRk/IEGUIUMgQ7xBgICA/AdxBH0gQwVDAAAAAAshREMAAAAAQQAqAoyBEEEAKgKQgRBBACoCqIM9lEEAKgKoxEZBACoCrMRGkpOUkyFFQQAgRbxBgICA/AdxBH0gRQVDAAAAAAs4AqSDPUEAKgKcgz1BACoCqMRGQQAqAqCDPUEAKgKkgz2UkpRBACoCrIM9QQAqArSDPZSSIUZBACBGvEGAgID8B3EEfSBGBUMAAAAACzgCsIM9QbiDPUEAKAKogRBB//8AcUECdGpD8wS1PkEAKgKwgz2UQwjlPB6SOAIAICJBuIM9QQAoAqiBEEEAKAK4g0FrQf//AHFBAnRqKgIAkkOamRk/QQAqAsSDQpSTIUdBvIPBAEEAKAKogRBB/x9xQQJ0aiBHOAIAQbyDwQBBACgCqIEQQQAoAryDQmtB/x9xQQJ0aioCACFIQQAgSLxBgICA/AdxBH0gSAVDAAAAAAs4AsCDQkOamRk/IEeUIUkgSbxBgICA/AdxBH0gSQVDAAAAAAshSkMAAAAAQQAqAoyBEEEAKgKQgRBBACoC1INClEEAKgL4w0ZBACoC/MNGkpOUkyFLQQAgS7xBgICA/AdxBH0gSwVDAAAAAAs4AtCDQkEAKgLIg0JBACoC+MNGQQAqAsyDQkEAKgLQg0KUkpRBACoC2INCQQAqAuCDQpSSIUxBACBMvEGAgID8B3EEfSBMBUMAAAAACzgC3INCQeSDwgBBACgCqIEQQf//AHFBAnRqQ/MEtT5BACoC3INClEMI5TwekjgCAEHkg8IAQQAoAqiBEEEAKALkg0ZrQf//AHFBAnRqKgIAICKSQ5qZGT9BACoC8MNGlJMhTUHog8YAQQAoAqiBEEH/D3FBAnRqIE04AgBB6IPGAEEAKAKogRBBACgC6MNGa0H/D3FBAnRqKgIAIU5BACBOvEGAgID8B3EEfSBOBUMAAAAACzgC7MNGQ5qZGT8gTZQhTyBPvEGAgID8B3EEfSBPBUMAAAAACyFQIFAgSpIhUSA+IEQgUZKSIVJBACoCvMEcQQAqAujBJUEAKgKUwipBACoCwMIzQQAqAuyCOEEAKgKYgz1BACoCxINCQQAqAvDDRiAmICwgMiA4IFKSkpKSkpKSkpKSkpIhU0EAIFO8QYCAgPwHcQR9IFMFQwAAAAALOAL0w0ZBACoC7II4QQAqApiDPUEAKgLEg0JBACoC8MNGIFKSkpKSQQAqArzBHEEAKgLowSVBACoClMIqQQAqAsDCMyAmICwgOCAykpKSkpKSkpMhVEEAIFS8QYCAgPwHcQR9IFQFQwAAAAALOAKAxEYgRCA+kiFVQQAqApTCKkEAKgLAwjNBACoCxINCQQAqAvDDRiAyIDggUZKSkpKSkkEAKgK8wRxBACoC6MElQQAqAuyCOEEAKgKYgz0gJiAsIFWSkpKSkpKTIVZBACBWvEGAgID8B3EEfSBWBUMAAAAACzgCjMRGQQAqArzBHEEAKgLowSVBACoCxINCQQAqAvDDRiAmICwgUZKSkpKSkkEAKgKUwipBACoCwMIzQQAqAuyCOEEAKgKYgz0gMiA4IFWSkpKSkpKTIVdBACBXvEGAgID8B3EEfSBXBUMAAAAACzgCmMRGIFAgRJIhWCBKID6SIVlBACoC6MElQQAqAsDCM0EAKgKYgz1BACoC8MNGICwgOCBYkpKSkpKSQQAqArzBHEEAKgKUwipBACoC7II4QQAqAsSDQiAmIDIgWZKSkpKSkpMhWkEAIFq8QYCAgPwHcQR9IFoFQwAAAAALOAKkxEZBACoCvMEcQQAqApTCKkEAKgKYgz1BACoC8MNGICYgMiBYkpKSkpKSQQAqAujBJUEAKgLAwjNBACoC7II4QQAqAsSDQiAsIDggWZKSkpKSkpMhW0EAIFu8QYCAgPwHcQR9IFsFQwAAAAALOAKwxEYgUCA+kiFcIEogRJIhXUEAKgK8wRxBACoCwMIzQQAqAuyCOEEAKgLww0YgJiA4IFySkpKSkpJBACoC6MElQQAqApTCKkEAKgKYgz1BACoCxINCICwgMiBdkpKSkpKSkyFeQQAgXrxBgICA/AdxBH0gXgVDAAAAAAs4ArzERkEAKgLowSVBACoClMIqQQAqAuyCOEEAKgLww0YgLCAyIFySkpKSkpJBACoCvMEcQQAqAsDCM0EAKgKYgz1BACoCxINCICYgOCBdkpKSkpKSkyFfQQAgX7xBgICA/AdxBH0gXwVDAAAAAAs4AsjERkOkcL0+QQAqAoDERkEAKgKMxEaSlCFgQQAqAtTERkEAKgLcxEaUIWEgYCBhQQAqAoCBEEEAKgLgxEaUkpMhYkEAIGK8QYCAgPwHcQR9IGIFQwAAAAALOALYxEZBACoCgIEQQQAqAtjERpQhY0MAAAA/IGNBACoC4MRGIGAgYZKSkiBjIGFBACoC4MRGkpIgYJOSlCFkQQAqAuTERkEAKgLsxEaUIWUgZCBlQQAqAvyAEEEAKgLwxEaUkpMhZkEAIGa8QYCAgPwHcQR9IGYFQwAAAAALOALoxEZBACoC/IAQQQAqAujERpQhZyAEIAZqQwAAAD9BACoClIAQIB4gHyBnQQAqAvDERiBkIGWSkpIgZyBlQQAqAvDERpKSIGSTkpSSlJQ4AgBDpHC9PkEAKgKAxEZBACoCjMRGk5QhaEEAKgLUxEZBACoC+MRGlCFpIGggaUEAKgKAgRBBACoC/MRGlJKTIWpBACBqvEGAgID8B3EEfSBqBUMAAAAACzgC9MRGQQAqAoCBEEEAKgL0xEaUIWtDAAAAPyBrQQAqAvzERiBoIGmSkpIgayBpQQAqAvzERpKSIGiTkpQhbEEAKgLkxEZBACoChMVGlCFtIGwgbUEAKgL8gBBBACoCiMVGlJKTIW5BACBuvEGAgID8B3EEfSBuBUMAAAAACzgCgMVGQQAqAvyAEEEAKgKAxUaUIW8gBSAGakMAAAA/QQAqApSAECAeIB8gb0EAKgKIxUYgbCBtkpKSIG8gbUEAKgKIxUaSkiBsk5KUkpSUOAIAQQBBACoClIAQOAKYgBBBAEEAKgKogBA4AqyAEEEAQQAqAriAEDgCvIAQQQBBACoCwIAQOALEgBBBAEEAKgLUgBA4AtiAEEEAQQAoAtyAEDYC4IAQQQBBACoC9IAQOAL4gBBBAEEAKgLwgBA4AvSAEEEAQQAqApSBEDgCmIEQQQBBACoCoIEQOAKkgRBBAEEAKAKogRBBAWo2AqiBEEEAQQAqArjBHDgCvMEcQQBBACoCyMEcOALMwRxBAEEAKgLUwRw4AtjBHEEAQQAqAuTBJTgC6MElQQBBACoC9MElOAL4wSVBAEEAKgKAwiU4AoTCJUEAQQAqApDCKjgClMIqQQBBACoCoMIqOAKkwipBAEEAKgKswio4ArDCKkEAQQAqArzCMzgCwMIzQQBBACoCzMIzOALQwjNBAEEAKgLYwjM4AtzCM0EAQQAqAuiCODgC7II4QQBBACoC+II4OAL8gjhBAEEAKgKEgzg4AoiDOEEAQQAqApSDPTgCmIM9QQBBACoCpIM9OAKogz1BAEEAKgKwgz04ArSDPUEAQQAqAsCDQjgCxINCQQBBACoC0INCOALUg0JBAEEAKgLcg0I4AuCDQkEAQQAqAuzDRjgC8MNGQQBBACoC+MNGOAL8w0ZBAEEAKgL0w0Y4AvjDRkEAQQAqAoTERjgCiMRGQQBBACoCgMRGOAKExEZBAEEAKgKQxEY4ApTERkEAQQAqAozERjgCkMRGQQBBACoCnMRGOAKgxEZBAEEAKgKYxEY4ApzERkEAQQAqAqjERjgCrMRGQQBBACoCpMRGOAKoxEZBAEEAKgK0xEY4ArjERkEAQQAqArDERjgCtMRGQQBBACoCwMRGOALExEZBAEEAKgK8xEY4AsDERkEAQQAqAszERjgC0MRGQQBBACoCyMRGOALMxEZBAEEAKgLcxEY4AuDERkEAQQAqAtjERjgC3MRGQQBBACoC7MRGOALwxEZBAEEAKgLoxEY4AuzERkEAQQAqAvjERjgC/MRGQQBBACoC9MRGOAL4xEZBAEEAKgKExUY4AojFRkEAQQAqAoDFRjgChMVGIAZBBGohBiAGQQQgAWxIBEAMAgwBCwsLC4WAgIAAAEEADwuFgICAAABBAg8Li4CAgAAAIAAgAWoqAgAPC4qAgIAAAEEAKAKAgBAPC46AgIAAACAAIAEQBSAAIAEQDgurmICAAAE8f0EAIQFBACECQQAhA0EAIQRBACEFQQAhBkEAIQdBACEIQQAhCUEAIQpBACELQQAhDEEAIQ1BACEOQQAhD0EAIRBBACERQQAhEkEAIRNBACEUQQAhFUEAIRZBACEXQQAhGEEAIRlBACEaQQAhG0EAIRxBACEdQQAhHkEAIR9BACEgQQAhIUEAISJBACEjQQAhJEEAISVBACEmQQAhJ0EAIShBACEpQQAhKkEAIStBACEsQQAhLUEAIS5BACEvQQAhMEEAITFBACEyQQAhM0EAITRBACE1QQAhNkEAITdBACE4QQAhOUEAITpBACE7QQAhPEEAIQEDQAJAQZSAECABQQJ0akMAAAAAOAIAIAFBAWohASABQQJIBEAMAgwBCwsLQQAhAgNAAkBBqIAQIAJBAnRqQwAAAAA4AgAgAkEBaiECIAJBAkgEQAwCDAELCwtBACEDA0ACQEG4gBAgA0ECdGpDAAAAADgCACADQQFqIQMgA0ECSARADAIMAQsLC0EAIQQDQAJAQcCAECAEQQJ0akMAAAAAOAIAIARBAWohBCAEQQJIBEAMAgwBCwsLQQAhBQNAAkBB1IAQIAVBAnRqQwAAAAA4AgAgBUEBaiEFIAVBAkgEQAwCDAELCwtBACEGA0ACQEHcgBAgBkECdGpBADYCACAGQQFqIQYgBkECSARADAIMAQsLC0EAIQcDQAJAQfCAECAHQQJ0akMAAAAAOAIAIAdBAWohByAHQQNIBEAMAgwBCwsLQQAhCANAAkBBlIEQIAhBAnRqQwAAAAA4AgAgCEEBaiEIIAhBAkgEQAwCDAELCwtBACEJA0ACQEGggRAgCUECdGpDAAAAADgCACAJQQFqIQkgCUECSARADAIMAQsLC0EAQQA2AqiBEEEAIQoDQAJAQayBECAKQQJ0akMAAAAAOAIAIApBAWohCiAKQYCAAkgEQAwCDAELCwtBACELA0ACQEGwgRggC0ECdGpDAAAAADgCACALQQFqIQsgC0GAgAFIBEAMAgwBCwsLQQAhDANAAkBBtIEcIAxBAnRqQwAAAAA4AgAgDEEBaiEMIAxBgBBIBEAMAgwBCwsLQQAhDQNAAkBBuMEcIA1BAnRqQwAAAAA4AgAgDUEBaiENIA1BAkgEQAwCDAELCwtBACEOA0ACQEHIwRwgDkECdGpDAAAAADgCACAOQQFqIQ4gDkECSARADAIMAQsLC0EAIQ8DQAJAQdTBHCAPQQJ0akMAAAAAOAIAIA9BAWohDyAPQQJIBEAMAgwBCwsLQQAhEANAAkBB3MEcIBBBAnRqQwAAAAA4AgAgEEEBaiEQIBBBgIACSARADAIMAQsLC0EAIREDQAJAQeDBJCARQQJ0akMAAAAAOAIAIBFBAWohESARQYAgSARADAIMAQsLC0EAIRIDQAJAQeTBJSASQQJ0akMAAAAAOAIAIBJBAWohEiASQQJIBEAMAgwBCwsLQQAhEwNAAkBB9MElIBNBAnRqQwAAAAA4AgAgE0EBaiETIBNBAkgEQAwCDAELCwtBACEUA0ACQEGAwiUgFEECdGpDAAAAADgCACAUQQFqIRQgFEECSARADAIMAQsLC0EAIRUDQAJAQYjCJSAVQQJ0akMAAAAAOAIAIBVBAWohFSAVQYCAAUgEQAwCDAELCwtBACEWA0ACQEGMwikgFkECdGpDAAAAADgCACAWQQFqIRYgFkGAIEgEQAwCDAELCwtBACEXA0ACQEGQwiogF0ECdGpDAAAAADgCACAXQQFqIRcgF0ECSARADAIMAQsLC0EAIRgDQAJAQaDCKiAYQQJ0akMAAAAAOAIAIBhBAWohGCAYQQJIBEAMAgwBCwsLQQAhGQNAAkBBrMIqIBlBAnRqQwAAAAA4AgAgGUEBaiEZIBlBAkgEQAwCDAELCwtBACEaA0ACQEG0wiogGkECdGpDAAAAADgCACAaQQFqIRogGkGAgAJIBEAMAgwBCwsLQQAhGwNAAkBBuMIyIBtBAnRqQwAAAAA4AgAgG0EBaiEbIBtBgCBIBEAMAgwBCwsLQQAhHANAAkBBvMIzIBxBAnRqQwAAAAA4AgAgHEEBaiEcIBxBAkgEQAwCDAELCwtBACEdA0ACQEHMwjMgHUECdGpDAAAAADgCACAdQQFqIR0gHUECSARADAIMAQsLC0EAIR4DQAJAQdjCMyAeQQJ0akMAAAAAOAIAIB5BAWohHiAeQQJIBEAMAgwBCwsLQQAhHwNAAkBB4MIzIB9BAnRqQwAAAAA4AgAgH0EBaiEfIB9BgIABSARADAIMAQsLC0EAISADQAJAQeTCNyAgQQJ0akMAAAAAOAIAICBBAWohICAgQYAQSARADAIMAQsLC0EAISEDQAJAQeiCOCAhQQJ0akMAAAAAOAIAICFBAWohISAhQQJIBEAMAgwBCwsLQQAhIgNAAkBB+II4ICJBAnRqQwAAAAA4AgAgIkEBaiEiICJBAkgEQAwCDAELCwtBACEjA0ACQEGEgzggI0ECdGpDAAAAADgCACAjQQFqISMgI0ECSARADAIMAQsLC0EAISQDQAJAQYyDOCAkQQJ0akMAAAAAOAIAICRBAWohJCAkQYCAAUgEQAwCDAELCwtBACElA0ACQEGQgzwgJUECdGpDAAAAADgCACAlQQFqISUgJUGAIEgEQAwCDAELCwtBACEmA0ACQEGUgz0gJkECdGpDAAAAADgCACAmQQFqISYgJkECSARADAIMAQsLC0EAIScDQAJAQaSDPSAnQQJ0akMAAAAAOAIAICdBAWohJyAnQQJIBEAMAgwBCwsLQQAhKANAAkBBsIM9IChBAnRqQwAAAAA4AgAgKEEBaiEoIChBAkgEQAwCDAELCwtBACEpA0ACQEG4gz0gKUECdGpDAAAAADgCACApQQFqISkgKUGAgAFIBEAMAgwBCwsLQQAhKgNAAkBBvIPBACAqQQJ0akMAAAAAOAIAICpBAWohKiAqQYAgSARADAIMAQsLC0EAISsDQAJAQcCDwgAgK0ECdGpDAAAAADgCACArQQFqISsgK0ECSARADAIMAQsLC0EAISwDQAJAQdCDwgAgLEECdGpDAAAAADgCACAsQQFqISwgLEECSARADAIMAQsLC0EAIS0DQAJAQdyDwgAgLUECdGpDAAAAADgCACAtQQFqIS0gLUECSARADAIMAQsLC0EAIS4DQAJAQeSDwgAgLkECdGpDAAAAADgCACAuQQFqIS4gLkGAgAFIBEAMAgwBCwsLQQAhLwNAAkBB6IPGACAvQQJ0akMAAAAAOAIAIC9BAWohLyAvQYAQSARADAIMAQsLC0EAITADQAJAQezDxgAgMEECdGpDAAAAADgCACAwQQFqITAgMEECSARADAIMAQsLC0EAITEDQAJAQfTDxgAgMUECdGpDAAAAADgCACAxQQFqITEgMUEDSARADAIMAQsLC0EAITIDQAJAQYDExgAgMkECdGpDAAAAADgCACAyQQFqITIgMkEDSARADAIMAQsLC0EAITMDQAJAQYzExgAgM0ECdGpDAAAAADgCACAzQQFqITMgM0EDSARADAIMAQsLC0EAITQDQAJAQZjExgAgNEECdGpDAAAAADgCACA0QQFqITQgNEEDSARADAIMAQsLC0EAITUDQAJAQaTExgAgNUECdGpDAAAAADgCACA1QQFqITUgNUEDSARADAIMAQsLC0EAITYDQAJAQbDExgAgNkECdGpDAAAAADgCACA2QQFqITYgNkEDSARADAIMAQsLC0EAITcDQAJAQbzExgAgN0ECdGpDAAAAADgCACA3QQFqITcgN0EDSARADAIMAQsLC0EAITgDQAJAQcjExgAgOEECdGpDAAAAADgCACA4QQFqITggOEEDSARADAIMAQsLC0EAITkDQAJAQdjExgAgOUECdGpDAAAAADgCACA5QQFqITkgOUEDSARADAIMAQsLC0EAIToDQAJAQejExgAgOkECdGpDAAAAADgCACA6QQFqITogOkEDSARADAIMAQsLC0EAITsDQAJAQfTExgAgO0ECdGpDAAAAADgCACA7QQFqITsgO0EDSARADAIMAQsLC0EAITwDQAJAQYDFxgAgPEECdGpDAAAAADgCACA8QQFqITwgPEEDSARADAIMAQsLCwuvn4CAAAFOfUNjFB1FQQAqAoSAEJUQBCECQwAAgD8gApUhA0MdQxNGQQAqAoSAEJUhBEOCZvdEQQAqAoSAEJUhBUNSRWE+QQAqAoSAEJRDAAAAP5KOIQZDAAAAAENVDN1AIAaUk0EAKgKEgBCVIQdDAAAAPyAHlBABIQhDHUMTR0EAKgKEgBCVEAAhCSAIQwAAAEAQAiEKQwAAgD8gCSAKlJMhC0MAAIA/IAqTIQxDAAAAACALQwAAAEAQAiAMQwAAAEAQApVDAACAv5KXkSENIAsgDJUhDkMAAIA/Q2MUHURBACoChIAQlRAElSEPQ9annDxBACoChIAQlEMAAAA/ko4hEEM4h4M+QQAqAoSAEJRDAAAAP5KOIRFDAAAAAENVDN1AIBGUk0EAKgKEgBCVIRJDAAAAPyASlBABIRMgE0MAAABAEAIhFEMAAIA/IAkgFJSTIRVDAACAPyAUkyEWQwAAAAAgFUMAAABAEAIgFkMAAABAEAKVQwAAgL+Sl5EhFyAVIBaVIRhDdenfPEEAKgKEgBCUQwAAAD+SjiEZQxTrRD5BACoChIAQlEMAAAA/ko4hGkMAAAAAQ1UM3UAgGpSTQQAqAoSAEJUhG0MAAAA/IBuUEAEhHCAcQwAAAEAQAiEdQwAAgD8gCSAdlJMhHkMAAIA/IB2TIR9DAAAAACAeQwAAAEAQAiAfQwAAAEAQApVDAACAv5KXkSEgIB4gH5UhIUOu8+88QQAqAoSAEJRDAAAAP5KOISJDN3BXPkEAKgKEgBCUQwAAAD+SjiEjQwAAAABDVQzdQCAjlJNBACoChIAQlSEkQwAAAD8gJJQQASElICVDAAAAQBACISZDAACAPyAJICaUkyEnQwAAgD8gJpMhKEMAAAAAICdDAAAAQBACIChDAAAAQBAClUMAAIC/kpeRISkgJyAolSEqQ40OyDxBACoChIAQlEMAAAA/ko4hK0MAAAA+QQAqAoSAEJRDAAAAP5KOISxDAAAAAENVDN1AICyUk0EAKgKEgBCVIS1DAAAAPyAtlBABIS4gLkMAAABAEAIhL0MAAIA/IAkgL5STITBDAACAPyAvkyExQwAAAAAgMEMAAABAEAIgMUMAAABAEAKVQwAAgL+Sl5EhMiAwIDGVITND8X5cPEEAKgKEgBCUQwAAAD+SjiE0Q7TnAj5BACoChIAQlEMAAAA/ko4hNUMAAAAAQ1UM3UAgNZSTQQAqAoSAEJUhNkMAAAA/IDaUEAEhNyA3QwAAAEAQAiE4QwAAgD8gCSA4lJMhOUMAAIA/IDiTITpDAAAAACA5QwAAAEAQAiA6QwAAAEAQApVDAACAv5KXkSE7IDkgOpUhPEMycwE9QQAqAoSAEJRDAAAAP5KOIT1D9+cyPkEAKgKEgBCUQwAAAD+SjiE+QwAAAABDVQzdQCA+lJNBACoChIAQlSE/QwAAAD8gP5QQASFAIEBDAAAAQBACIUFDAACAPyAJIEGUkyFCQwAAgD8gQZMhQ0MAAAAAIEJDAAAAQBACIENDAAAAQBAClUMAAIC/kpeRIUQgQiBDlSFFQyuhuzxBACoChIAQlEMAAAA/ko4hRkPZzRw+QQAqAoSAEJRDAAAAP5KOIUdDAAAAAENVDN1AIEeUk0EAKgKEgBCVIUhDAAAAPyBIlBABIUkgSUMAAABAEAIhSkMAAIA/IAkgSpSTIUtDAACAPyBKkyFMQwAAAAAgS0MAAABAEAIgTEMAAABAEAKVQwAAgL+Sl5EhTSBLIEyVIU5DqKymPEEAKgKEgBCUQwAAAD+SjiFPQQAgATYCgIAQQQBDAIA7SEMAAIA/QQAoAoCAELKXljgChIAQQQBDZmYwQkEAKgKEgBCVOAKIgBBBAEMAAIA/QQAqAoiAEJM4ApCAEENjFB1FQQAqAoSAEJUQBCECQwAAgD8gApUhA0EAQwAAgD8gA0PNzEw+kiAClUMAAIA/kpU4ApyAEEEAQwAAgD9BACoChIAQlTgCsIAQQQBDAACAP0MK1yM8QQAqAoSAEJSXOALIgBBBAEMAAIA/QQAqAsiAEJU4AsyAEEEAQwAAgD9DAACAP0PNzMw+QQAqAoSAEJSXlTgC5IAQQQAgA0PNzEy+kiAClUMAAIA/kjgC6IAQQQBDAAAAQEMAAIA/QwAAgD8gAkMAAABAEAKVk5Q4AuyAEEMdQxNGQQAqAoSAEJUhBEEAQwAAgD8gBJMgBEMAAIA/kpU4AvyAEEOCZvdEQQAqAoSAEJUhBUEAQwAAgD8gBZMgBUMAAIA/kpU4AoCBEENSRWE+QQAqAoSAEJRDAAAAP5KOIQZDAAAAAENVDN1AIAaUk0EAKgKEgBCVIQdDAAAAPyAHlBABIQhDHUMTR0EAKgKEgBCVEAAhCSAIQwAAAEAQAiEKQwAAgD8gCSAKlJMhC0MAAIA/IAqTIQxDAAAAACALQwAAAEAQAiAMQwAAAEAQApVDAACAv5KXkSENIAsgDJUhDkEAIAggDUMAAIA/IA6TkpQ4AoSBEEEAQ6uqqj4gB5QQASAIlUMAAIC/kjgCiIEQQwAAgD9DYxQdREEAKgKEgBCVEASVIQ9BAEMAAIA/IA9DAACAP5KVOAKMgRBBAEMAAIA/IA+TOAKQgRBBACAOIA2TOAKcgRBD1qecPEEAKgKEgBCUQwAAAD+SjiEQQQBDAACARkMAAAAAIAYgEJOXlqg2AqyBGEEAQwAAAEZDAAAAAEOPwnU9QQAqAoSAEJSXlqg2ArCBHEEAQwAAgERDAAAAACAQQwAAgL+Sl5aoNgK0wRxDOIeDPkEAKgKEgBCUQwAAAD+SjiERQwAAAABDVQzdQCARlJNBACoChIAQlSESQwAAAD8gEpQQASETIBNDAAAAQBACIRRDAACAPyAJIBSUkyEVQwAAgD8gFJMhFkMAAAAAIBVDAAAAQBACIBZDAAAAQBAClUMAAIC/kpeRIRcgFSAWlSEYQQAgEyAXQwAAgD8gGJOSlDgCwMEcQQBDq6qqPiASlBABIBOVQwAAgL+SOALEwRxBACAYIBeTOALQwRxDdenfPEEAKgKEgBCUQwAAAD+SjiEZQQBDAACARkMAAAAAIBEgGZOXlqg2AtzBJEEAQwAAAEVDAAAAACAZQwAAgL+Sl5aoNgLgwSVDFOtEPkEAKgKEgBCUQwAAAD+SjiEaQwAAAABDVQzdQCAalJNBACoChIAQlSEbQwAAAD8gG5QQASEcIBxDAAAAQBACIR1DAACAPyAJIB2UkyEeQwAAgD8gHZMhH0MAAAAAIB5DAAAAQBACIB9DAAAAQBAClUMAAIC/kpeRISAgHiAflSEhQQAgHCAgQwAAgD8gIZOSlDgC7MElQQBDq6qqPiAblBABIByVQwAAgL+SOALwwSVBACAhICCTOAL8wSVDrvPvPEEAKgKEgBCUQwAAAD+SjiEiQQBDAAAARkMAAAAAIBogIpOXlqg2AojCKUEAQwAAAEVDAAAAACAiQwAAgL+Sl5aoNgKMwipDN3BXPkEAKgKEgBCUQwAAAD+SjiEjQwAAAABDVQzdQCAjlJNBACoChIAQlSEkQwAAAD8gJJQQASElICVDAAAAQBACISZDAACAPyAJICaUkyEnQwAAgD8gJpMhKEMAAAAAICdDAAAAQBACIChDAAAAQBAClUMAAIC/kpeRISkgJyAolSEqQQAgJSApQwAAgD8gKpOSlDgCmMIqQQBDq6qqPiAklBABICWVQwAAgL+SOAKcwipBACAqICmTOAKowipDjQ7IPEEAKgKEgBCUQwAAAD+SjiErQQBDAACARkMAAAAAICMgK5OXlqg2ArTCMkEAQwAAAEVDAAAAACArQwAAgL+Sl5aoNgK4wjNDAAAAPkEAKgKEgBCUQwAAAD+SjiEsQwAAAABDVQzdQCAslJNBACoChIAQlSEtQwAAAD8gLZQQASEuIC5DAAAAQBACIS9DAACAPyAJIC+UkyEwQwAAgD8gL5MhMUMAAAAAIDBDAAAAQBACIDFDAAAAQBAClUMAAIC/kpeRITIgMCAxlSEzQQAgLiAyQwAAgD8gM5OSlDgCxMIzQQBDq6qqPiAtlBABIC6VQwAAgL+SOALIwjNBACAzIDKTOALUwjND8X5cPEEAKgKEgBCUQwAAAD+SjiE0QQBDAAAARkMAAAAAICwgNJOXlqg2AuDCN0EAQwAAgERDAAAAACA0QwAAgL+Sl5aoNgLkgjhDtOcCPkEAKgKEgBCUQwAAAD+SjiE1QwAAAABDVQzdQCA1lJNBACoChIAQlSE2QwAAAD8gNpQQASE3IDdDAAAAQBACIThDAACAPyAJIDiUkyE5QwAAgD8gOJMhOkMAAAAAIDlDAAAAQBACIDpDAAAAQBAClUMAAIC/kpeRITsgOSA6lSE8QQAgNyA7QwAAgD8gPJOSlDgC8II4QQBDq6qqPiA2lBABIDeVQwAAgL+SOAL0gjhBACA8IDuTOAKAgzhDMnMBPUEAKgKEgBCUQwAAAD+SjiE9QQBDAAAARkMAAAAAIDUgPZOXlqg2AoyDPEEAQwAAAEVDAAAAACA9QwAAgL+Sl5aoNgKQgz1D9+cyPkEAKgKEgBCUQwAAAD+SjiE+QwAAAABDVQzdQCA+lJNBACoChIAQlSE/QwAAAD8gP5QQASFAIEBDAAAAQBACIUFDAACAPyAJIEGUkyFCQwAAgD8gQZMhQ0MAAAAAIEJDAAAAQBACIENDAAAAQBAClUMAAIC/kpeRIUQgQiBDlSFFQQAgQCBEQwAAgD8gRZOSlDgCnIM9QQBDq6qqPiA/lBABIECVQwAAgL+SOAKggz1BACBFIESTOAKsgz1DK6G7PEEAKgKEgBCUQwAAAD+SjiFGQQBDAAAARkMAAAAAID4gRpOXlqg2AriDQUEAQwAAAEVDAAAAACBGQwAAgL+Sl5aoNgK8g0JD2c0cPkEAKgKEgBCUQwAAAD+SjiFHQwAAAABDVQzdQCBHlJNBACoChIAQlSFIQwAAAD8gSJQQASFJIElDAAAAQBACIUpDAACAPyAJIEqUkyFLQwAAgD8gSpMhTEMAAAAAIEtDAAAAQBACIExDAAAAQBAClUMAAIC/kpeRIU0gSyBMlSFOQQAgSSBNQwAAgD8gTpOSlDgCyINCQQBDq6qqPiBIlBABIEmVQwAAgL+SOALMg0JBACBOIE2TOALYg0JDqKymPEEAKgKEgBCUQwAAAD+SjiFPQQBDAAAARkMAAAAAIEcgT5OXlqg2AuSDRkEAQwAAgERDAAAAACBPQwAAgL+Sl5aoNgLow0ZBAEMAAAAAIAUQAEEAKgKAgRBDAACAP5KUkzgC1MRGQQBDAAAAACAEEABBACoC/IAQQwAAgD+SlJM4AuTERguQgICAAAAgACABEA0gABAPIAAQDAu+gICAAABBAEMAAMDAOAKMgBBBAEPNzMw+OAKggBBBAEMAAAAAOAKkgBBBAEMAANxDOAK0gBBBAEMAAAAAOALQgBALkICAgAAAIAAgAUgEfyABBSAACw8LkICAgAAAIAAgAUgEfyAABSABCw8LjICAgAAAIAAgAWogAjgCAAsL+62AgAABAEEAC/QteyJuYW1lIjogInNvdW5kIiwiZmlsZW5hbWUiOiAic291bmQuZHNwIiwidmVyc2lvbiI6ICIyLjQwLjEyIiwiY29tcGlsZV9vcHRpb25zIjogIi1sYW5nIHdhc20taWIgLWNuIHNvdW5kIC1lcyAxIC1tY2QgMTYgLXNpbmdsZSAtZnR6IDIiLCJpbmNsdWRlX3BhdGhuYW1lcyI6IFsiL3Vzci9sb2NhbC9zaGFyZS9mYXVzdCIsIi91c3IvbG9jYWwvc2hhcmUvZmF1c3QiLCIvdXNyL3NoYXJlL2ZhdXN0IiwiLiIsIi90bXAvc2Vzc2lvbnMvQkZCNEZEQjQ1OTdEN0MzOENGRjE2QjM0QUExNkI0OEU1RkEyREY3Qi93ZWIvd2FzbWpzLXdvcmtsZXQiXSwic2l6ZSI6IDExNTU3NDAsImlucHV0cyI6IDAsIm91dHB1dHMiOiAyLCJtZXRhIjogWyB7ICJiYXNpY3NfbGliX25hbWUiOiAiRmF1c3QgQmFzaWMgRWxlbWVudCBMaWJyYXJ5IiB9LHsgImJhc2ljc19saWJfdmVyc2lvbiI6ICIwLjgiIH0seyAiY29tcGlsZV9vcHRpb25zIjogIi1zaW5nbGUgLXNjYWwgLUkgbGlicmFyaWVzLyAtSSBwcm9qZWN0LyAtbGFuZyB3YXNtIiB9LHsgImRlbGF5c19saWJfbmFtZSI6ICJGYXVzdCBEZWxheSBMaWJyYXJ5IiB9LHsgImRlbGF5c19saWJfdmVyc2lvbiI6ICIwLjEiIH0seyAiZGVtb3NfbGliX25hbWUiOiAiRmF1c3QgRGVtb3MgTGlicmFyeSIgfSx7ICJkZW1vc19saWJfdmVyc2lvbiI6ICIwLjEiIH0seyAiZGVtb3NfbGliX3ppdGFfbGlnaHRfYXV0aG9yIjogIkp1bGl1cyBPLiBTbWl0aCBJSUkiIH0seyAiZGVtb3NfbGliX3ppdGFfbGlnaHRfbGljZW5jZSI6ICJNSVQiIH0seyAiZW52ZWxvcGVzX2xpYl9hcl9hdXRob3IiOiAiWWFubiBPcmxhcmV5LCBTdMOpcGhhbmUgTGV0eiIgfSx7ICJlbnZlbG9wZXNfbGliX2F1dGhvciI6ICJHUkFNRSIgfSx7ICJlbnZlbG9wZXNfbGliX2NvcHlyaWdodCI6ICJHUkFNRSIgfSx7ICJlbnZlbG9wZXNfbGliX2xpY2Vuc2UiOiAiTEdQTCB3aXRoIGV4Y2VwdGlvbiIgfSx7ICJlbnZlbG9wZXNfbGliX25hbWUiOiAiRmF1c3QgRW52ZWxvcGUgTGlicmFyeSIgfSx7ICJlbnZlbG9wZXNfbGliX3ZlcnNpb24iOiAiMC4yIiB9LHsgImZpbGVuYW1lIjogInNvdW5kLmRzcCIgfSx7ICJmaWx0ZXJzX2xpYl9hbGxwYXNzX2NvbWJfYXV0aG9yIjogIkp1bGl1cyBPLiBTbWl0aCBJSUkiIH0seyAiZmlsdGVyc19saWJfYWxscGFzc19jb21iX2NvcHlyaWdodCI6ICJDb3B5cmlnaHQgKEMpIDIwMDMtMjAxOSBieSBKdWxpdXMgTy4gU21pdGggSUlJIDxqb3NAY2NybWEuc3RhbmZvcmQuZWR1PiIgfSx7ICJmaWx0ZXJzX2xpYl9hbGxwYXNzX2NvbWJfbGljZW5zZSI6ICJNSVQtc3R5bGUgU1RLLTQuMyBsaWNlbnNlIiB9LHsgImZpbHRlcnNfbGliX2Zpcl9hdXRob3IiOiAiSnVsaXVzIE8uIFNtaXRoIElJSSIgfSx7ICJmaWx0ZXJzX2xpYl9maXJfY29weXJpZ2h0IjogIkNvcHlyaWdodCAoQykgMjAwMy0yMDE5IGJ5IEp1bGl1cyBPLiBTbWl0aCBJSUkgPGpvc0BjY3JtYS5zdGFuZm9yZC5lZHU+IiB9LHsgImZpbHRlcnNfbGliX2Zpcl9saWNlbnNlIjogIk1JVC1zdHlsZSBTVEstNC4zIGxpY2Vuc2UiIH0seyAiZmlsdGVyc19saWJfaWlyX2F1dGhvciI6ICJKdWxpdXMgTy4gU21pdGggSUlJIiB9LHsgImZpbHRlcnNfbGliX2lpcl9jb3B5cmlnaHQiOiAiQ29weXJpZ2h0IChDKSAyMDAzLTIwMTkgYnkgSnVsaXVzIE8uIFNtaXRoIElJSSA8am9zQGNjcm1hLnN0YW5mb3JkLmVkdT4iIH0seyAiZmlsdGVyc19saWJfaWlyX2xpY2Vuc2UiOiAiTUlULXN0eWxlIFNUSy00LjMgbGljZW5zZSIgfSx7ICJmaWx0ZXJzX2xpYl9sb3dwYXNzMF9oaWdocGFzczEiOiAiQ29weXJpZ2h0IChDKSAyMDAzLTIwMTkgYnkgSnVsaXVzIE8uIFNtaXRoIElJSSA8am9zQGNjcm1hLnN0YW5mb3JkLmVkdT4iIH0seyAiZmlsdGVyc19saWJfbG93cGFzczBfaGlnaHBhc3MxX2F1dGhvciI6ICJKdWxpdXMgTy4gU21pdGggSUlJIiB9LHsgImZpbHRlcnNfbGliX2xvd3Bhc3NfYXV0aG9yIjogIkp1bGl1cyBPLiBTbWl0aCBJSUkiIH0seyAiZmlsdGVyc19saWJfbG93cGFzc19jb3B5cmlnaHQiOiAiQ29weXJpZ2h0IChDKSAyMDAzLTIwMTkgYnkgSnVsaXVzIE8uIFNtaXRoIElJSSA8am9zQGNjcm1hLnN0YW5mb3JkLmVkdT4iIH0seyAiZmlsdGVyc19saWJfbG93cGFzc19saWNlbnNlIjogIk1JVC1zdHlsZSBTVEstNC4zIGxpY2Vuc2UiIH0seyAiZmlsdGVyc19saWJfbmFtZSI6ICJGYXVzdCBGaWx0ZXJzIExpYnJhcnkiIH0seyAiZmlsdGVyc19saWJfcGVha19lcV9ybV9hdXRob3IiOiAiSnVsaXVzIE8uIFNtaXRoIElJSSIgfSx7ICJmaWx0ZXJzX2xpYl9wZWFrX2VxX3JtX2NvcHlyaWdodCI6ICJDb3B5cmlnaHQgKEMpIDIwMDMtMjAxOSBieSBKdWxpdXMgTy4gU21pdGggSUlJIDxqb3NAY2NybWEuc3RhbmZvcmQuZWR1PiIgfSx7ICJmaWx0ZXJzX2xpYl9wZWFrX2VxX3JtX2xpY2Vuc2UiOiAiTUlULXN0eWxlIFNUSy00LjMgbGljZW5zZSIgfSx7ICJmaWx0ZXJzX2xpYl9yZXNvbmxwX2F1dGhvciI6ICJKdWxpdXMgTy4gU21pdGggSUlJIiB9LHsgImZpbHRlcnNfbGliX3Jlc29ubHBfY29weXJpZ2h0IjogIkNvcHlyaWdodCAoQykgMjAwMy0yMDE5IGJ5IEp1bGl1cyBPLiBTbWl0aCBJSUkgPGpvc0BjY3JtYS5zdGFuZm9yZC5lZHU+IiB9LHsgImZpbHRlcnNfbGliX3Jlc29ubHBfbGljZW5zZSI6ICJNSVQtc3R5bGUgU1RLLTQuMyBsaWNlbnNlIiB9LHsgImZpbHRlcnNfbGliX3RmMV9hdXRob3IiOiAiSnVsaXVzIE8uIFNtaXRoIElJSSIgfSx7ICJmaWx0ZXJzX2xpYl90ZjFfY29weXJpZ2h0IjogIkNvcHlyaWdodCAoQykgMjAwMy0yMDE5IGJ5IEp1bGl1cyBPLiBTbWl0aCBJSUkgPGpvc0BjY3JtYS5zdGFuZm9yZC5lZHU+IiB9LHsgImZpbHRlcnNfbGliX3RmMV9saWNlbnNlIjogIk1JVC1zdHlsZSBTVEstNC4zIGxpY2Vuc2UiIH0seyAiZmlsdGVyc19saWJfdGYxc19hdXRob3IiOiAiSnVsaXVzIE8uIFNtaXRoIElJSSIgfSx7ICJmaWx0ZXJzX2xpYl90ZjFzX2NvcHlyaWdodCI6ICJDb3B5cmlnaHQgKEMpIDIwMDMtMjAxOSBieSBKdWxpdXMgTy4gU21pdGggSUlJIDxqb3NAY2NybWEuc3RhbmZvcmQuZWR1PiIgfSx7ICJmaWx0ZXJzX2xpYl90ZjFzX2xpY2Vuc2UiOiAiTUlULXN0eWxlIFNUSy00LjMgbGljZW5zZSIgfSx7ICJmaWx0ZXJzX2xpYl90ZjJfYXV0aG9yIjogIkp1bGl1cyBPLiBTbWl0aCBJSUkiIH0seyAiZmlsdGVyc19saWJfdGYyX2NvcHlyaWdodCI6ICJDb3B5cmlnaHQgKEMpIDIwMDMtMjAxOSBieSBKdWxpdXMgTy4gU21pdGggSUlJIDxqb3NAY2NybWEuc3RhbmZvcmQuZWR1PiIgfSx7ICJmaWx0ZXJzX2xpYl90ZjJfbGljZW5zZSI6ICJNSVQtc3R5bGUgU1RLLTQuMyBsaWNlbnNlIiB9LHsgImZpbHRlcnNfbGliX3RmMnNfYXV0aG9yIjogIkp1bGl1cyBPLiBTbWl0aCBJSUkiIH0seyAiZmlsdGVyc19saWJfdGYyc19jb3B5cmlnaHQiOiAiQ29weXJpZ2h0IChDKSAyMDAzLTIwMTkgYnkgSnVsaXVzIE8uIFNtaXRoIElJSSA8am9zQGNjcm1hLnN0YW5mb3JkLmVkdT4iIH0seyAiZmlsdGVyc19saWJfdGYyc19saWNlbnNlIjogIk1JVC1zdHlsZSBTVEstNC4zIGxpY2Vuc2UiIH0seyAiZmlsdGVyc19saWJfdmVyc2lvbiI6ICIwLjMiIH0seyAibGlicmFyeV9wYXRoMCI6ICIvbGlicmFyaWVzL3N0ZGZhdXN0LmxpYiIgfSx7ICJsaWJyYXJ5X3BhdGgxIjogIi9saWJyYXJpZXMvb3NjaWxsYXRvcnMubGliIiB9LHsgImxpYnJhcnlfcGF0aDEwIjogIi9saWJyYXJpZXMvc2lnbmFscy5saWIiIH0seyAibGlicmFyeV9wYXRoMTEiOiAiL2xpYnJhcmllcy9yb3V0ZXMubGliIiB9LHsgImxpYnJhcnlfcGF0aDIiOiAiL2xpYnJhcmllcy9wbGF0Zm9ybS5saWIiIH0seyAibGlicmFyeV9wYXRoMyI6ICIvbGlicmFyaWVzL21hdGhzLmxpYiIgfSx7ICJsaWJyYXJ5X3BhdGg0IjogIi9saWJyYXJpZXMvYmFzaWNzLmxpYiIgfSx7ICJsaWJyYXJ5X3BhdGg1IjogIi9saWJyYXJpZXMvZW52ZWxvcGVzLmxpYiIgfSx7ICJsaWJyYXJ5X3BhdGg2IjogIi9saWJyYXJpZXMvZmlsdGVycy5saWIiIH0seyAibGlicmFyeV9wYXRoNyI6ICIvbGlicmFyaWVzL2RlbW9zLmxpYiIgfSx7ICJsaWJyYXJ5X3BhdGg4IjogIi9saWJyYXJpZXMvcmV2ZXJicy5saWIiIH0seyAibGlicmFyeV9wYXRoOSI6ICIvbGlicmFyaWVzL2RlbGF5cy5saWIiIH0seyAibWF0aHNfbGliX2F1dGhvciI6ICJHUkFNRSIgfSx7ICJtYXRoc19saWJfY29weXJpZ2h0IjogIkdSQU1FIiB9LHsgIm1hdGhzX2xpYl9saWNlbnNlIjogIkxHUEwgd2l0aCBleGNlcHRpb24iIH0seyAibWF0aHNfbGliX25hbWUiOiAiRmF1c3QgTWF0aCBMaWJyYXJ5IiB9LHsgIm1hdGhzX2xpYl92ZXJzaW9uIjogIjIuNSIgfSx7ICJuYW1lIjogInNvdW5kIiB9LHsgIm9zY2lsbGF0b3JzX2xpYl9uYW1lIjogIkZhdXN0IE9zY2lsbGF0b3IgTGlicmFyeSIgfSx7ICJvc2NpbGxhdG9yc19saWJfdmVyc2lvbiI6ICIwLjMiIH0seyAicGxhdGZvcm1fbGliX25hbWUiOiAiR2VuZXJpYyBQbGF0Zm9ybSBMaWJyYXJ5IiB9LHsgInBsYXRmb3JtX2xpYl92ZXJzaW9uIjogIjAuMiIgfSx7ICJyZXZlcmJzX2xpYl9uYW1lIjogIkZhdXN0IFJldmVyYiBMaWJyYXJ5IiB9LHsgInJldmVyYnNfbGliX3ZlcnNpb24iOiAiMC4yIiB9LHsgInJvdXRlc19saWJfaGFkYW1hcmRfYXV0aG9yIjogIlJlbXkgTXVsbGVyLCByZXZpc2VkIGJ5IFJvbWFpbiBNaWNob24iIH0seyAicm91dGVzX2xpYl9uYW1lIjogIkZhdXN0IFNpZ25hbCBSb3V0aW5nIExpYnJhcnkiIH0seyAicm91dGVzX2xpYl92ZXJzaW9uIjogIjAuMiIgfSx7ICJzaWduYWxzX2xpYl9uYW1lIjogIkZhdXN0IFNpZ25hbCBSb3V0aW5nIExpYnJhcnkiIH0seyAic2lnbmFsc19saWJfdmVyc2lvbiI6ICIwLjMiIH0seyAidmVyc2lvbiI6ICIyLjQ0LjUiIH1dLCJ1aSI6IFsgeyJ0eXBlIjogInZncm91cCIsImxhYmVsIjogInNvdW5kIiwiaXRlbXMiOiBbIHsidHlwZSI6ICJoZ3JvdXAiLCJsYWJlbCI6ICJaaXRhIExpZ2h0IiwiaXRlbXMiOiBbIHsidHlwZSI6ICJ2c2xpZGVyIiwibGFiZWwiOiAiRHJ5L1dldCBNaXgiLCJzaG9ydG5hbWUiOiAiV2V0X01peCIsImFkZHJlc3MiOiAiL3NvdW5kL1ppdGFfTGlnaHQvRHJ5L1dldF9NaXgiLCJpbmRleCI6IDI2MjE4MCwibWV0YSI6IFt7ICIxIjogIiIgfSx7ICJzdHlsZSI6ICJrbm9iIiB9LHsgInRvb2x0aXAiOiAiLTEgPSBkcnksIDEgPSB3ZXQiIH1dLCJpbml0IjogMCwibWluIjogLTEsIm1heCI6IDEsInN0ZXAiOiAwLjAxfSx7InR5cGUiOiAidnNsaWRlciIsImxhYmVsIjogIkxldmVsIiwic2hvcnRuYW1lIjogIkxldmVsIiwiYWRkcmVzcyI6ICIvc291bmQvWml0YV9MaWdodC9MZXZlbCIsImluZGV4IjogMjYyMTU2LCJtZXRhIjogW3sgIjIiOiAiIiB9LHsgInN0eWxlIjogImtub2IiIH0seyAidG9vbHRpcCI6ICJPdXRwdXQgc2NhbGUgICAgICAgICBmYWN0b3IiIH0seyAidW5pdCI6ICJkQiIgfV0sImluaXQiOiAtNiwibWluIjogLTcwLCJtYXgiOiA0MCwic3RlcCI6IDAuMX1dfSx7InR5cGUiOiAiaHNsaWRlciIsImxhYmVsIjogImZyZXEiLCJzaG9ydG5hbWUiOiAiZnJlcSIsImFkZHJlc3MiOiAiL3NvdW5kL2ZyZXEiLCJpbmRleCI6IDI2MjE5NiwiaW5pdCI6IDQ0MCwibWluIjogMjAsIm1heCI6IDI0MDAwLCJzdGVwIjogMX0seyJ0eXBlIjogImhzbGlkZXIiLCJsYWJlbCI6ICJnYWluIiwic2hvcnRuYW1lIjogImdhaW4iLCJhZGRyZXNzIjogIi9zb3VuZC9nYWluIiwiaW5kZXgiOiAyNjIxNzYsImluaXQiOiAwLjQsIm1pbiI6IDAsIm1heCI6IDEsInN0ZXAiOiAwLjAxfSx7InR5cGUiOiAiYnV0dG9uIiwibGFiZWwiOiAiZ2F0ZSIsInNob3J0bmFtZSI6ICJnYXRlIiwiYWRkcmVzcyI6ICIvc291bmQvZ2F0ZSIsImluZGV4IjogMjYyMjI0fV19XX0="; }

/*
 faust2wasm: GRAME 2017-2019
*/

'use strict';

if (typeof (AudioWorkletNode) === "undefined") {
    alert("AudioWorklet is not supported in this browser !")
}

class soundNode extends AudioWorkletNode {

    constructor(context, baseURL, options) {
        super(context, 'sound', options);

        this.baseURL = baseURL;
        this.json = options.processorOptions.json;
        this.json_object = JSON.parse(this.json);

        // JSON parsing functions
        this.parse_ui = function (ui, obj) {
            for (var i = 0; i < ui.length; i++) {
                this.parse_group(ui[i], obj);
            }
        }

        this.parse_group = function (group, obj) {
            if (group.items) {
                this.parse_items(group.items, obj);
            }
        }

        this.parse_items = function (items, obj) {
            for (var i = 0; i < items.length; i++) {
                this.parse_item(items[i], obj);
            }
        }

        this.parse_item = function (item, obj) {
            if (item.type === "vgroup"
                || item.type === "hgroup"
                || item.type === "tgroup") {
                this.parse_items(item.items, obj);
            } else if (item.type === "hbargraph"
                || item.type === "vbargraph") {
                // Keep bargraph adresses
                obj.outputs_items.push(item.address);
            } else if (item.type === "vslider"
                || item.type === "hslider"
                || item.type === "button"
                || item.type === "checkbox"
                || item.type === "nentry") {
                // Keep inputs adresses
                obj.inputs_items.push(item.address);
                obj.descriptor.push(item);
                // Decode MIDI
                if (item.meta !== undefined) {
                    for (var i = 0; i < item.meta.length; i++) {
                        if (item.meta[i].midi !== undefined) {
                            if (item.meta[i].midi.trim() === "pitchwheel") {
                                obj.fPitchwheelLabel.push({
                                    path: item.address,
                                    min: parseFloat(item.min),
                                    max: parseFloat(item.max)
                                });
                            } else if (item.meta[i].midi.trim().split(" ")[0] === "ctrl") {
                                obj.fCtrlLabel[parseInt(item.meta[i].midi.trim().split(" ")[1])]
                                    .push({
                                        path: item.address,
                                        min: parseFloat(item.min),
                                        max: parseFloat(item.max)
                                    });
                            }
                        }
                    }
                }
                // Define setXXX/getXXX, replacing '/c' with 'C' everywhere in the string
                var set_name = "set" + item.address;
                var get_name = "get" + item.address;
                set_name = set_name.replace(/\/./g, (x) => { return x.substr(1, 1).toUpperCase(); });
                get_name = get_name.replace(/\/./g, (x) => { return x.substr(1, 1).toUpperCase(); });
                obj[set_name] = (val) => { obj.setParamValue(item.address, val); };
                obj[get_name] = () => { return obj.getParamValue(item.address); };
                //console.log(set_name);
                //console.log(get_name);
            }
        }

        this.output_handler = null;

        // input/output items
        this.inputs_items = [];
        this.outputs_items = [];
        this.descriptor = [];

        // MIDI
        this.fPitchwheelLabel = [];
        this.fCtrlLabel = new Array(128);
        for (var i = 0; i < this.fCtrlLabel.length; i++) { this.fCtrlLabel[i] = []; }

        // Parse UI
        this.parse_ui(this.json_object.ui, this);

        // Set message handler
        this.port.onmessage = this.handleMessage.bind(this);
        try {
            if (this.parameters) this.parameters.forEach(p => p.automationRate = "k-rate");
        } catch (e) { }
    }

    // To be called by the message port with messages coming from the processor
    handleMessage(event) {
        var msg = event.data;
        if (this.output_handler) {
            this.output_handler(msg.path, msg.value);
        }
    }

    // Public API

    /**
     * Destroy the node, deallocate resources.
     */
    destroy() {
        this.port.postMessage({ type: "destroy" });
        this.port.close();
    }

    /**
     *  Returns a full JSON description of the DSP.
     */
    getJSON() {
        return this.json;
    }

    // For WAP
    async getMetadata() {
        return new Promise(resolve => {
            let real_url = (this.baseURL === "") ? "main.json" : (this.baseURL + "/main.json");
            fetch(real_url).then(responseJSON => {
                return responseJSON.json();
            }).then(json => {
                resolve(json);
            })
        });
    }

    /**
     *  Set the control value at a given path.
     *
     * @param path - a path to the control
     * @param val - the value to be set
     */
    setParamValue(path, val) {
        // Needed for sample accurate control
        this.parameters.get(path).setValueAtTime(val, 0);
    }

    // For WAP
    setParam(path, val) {
        // Needed for sample accurate control
        this.parameters.get(path).setValueAtTime(val, 0);
    }

    /**
     *  Get the control value at a given path.
     *
     * @return the current control value
     */
    getParamValue(path) {
        return this.parameters.get(path).value;
    }

    // For WAP
    getParam(path) {
        return this.parameters.get(path).value;
    }

    /**
     * Setup a control output handler with a function of type (path, value)
     * to be used on each generated output value. This handler will be called
     * each audio cycle at the end of the 'compute' method.
     *
     * @param handler - a function of type function(path, value)
     */
    setOutputParamHandler(handler) {
        this.output_handler = handler;
    }

    /**
     * Get the current output handler.
     */
    getOutputParamHandler() {
        return this.output_handler;
    }

    getNumInputs() {
        return parseInt(this.json_object.inputs);
    }

    getNumOutputs() {
        return parseInt(this.json_object.outputs);
    }

    // For WAP
    inputChannelCount() {
        return parseInt(this.json_object.inputs);
    }

    outputChannelCount() {
        return parseInt(this.json_object.outputs);
    }

    /**
     * Returns an array of all input paths (to be used with setParamValue/getParamValue)
     */
    getParams() {
        return this.inputs_items;
    }

    // For WAP
    getDescriptor() {
        var desc = {};
        for (const item in this.descriptor) {
            if (this.descriptor.hasOwnProperty(item)) {
                if (this.descriptor[item].label != "bypass") {
                    desc = Object.assign({ [this.descriptor[item].label]: { minValue: this.descriptor[item].min, maxValue: this.descriptor[item].max, defaultValue: this.descriptor[item].init } }, desc);
                }
            }
        }
        return desc;
    }

    /**
     * Control change
     *
     * @param channel - the MIDI channel (0..15, not used for now)
     * @param ctrl - the MIDI controller number (0..127)
     * @param value - the MIDI controller value (0..127)
     */
    ctrlChange(channel, ctrl, value) {
        if (this.fCtrlLabel[ctrl] !== []) {
            for (var i = 0; i < this.fCtrlLabel[ctrl].length; i++) {
                var path = this.fCtrlLabel[ctrl][i].path;
                this.setParamValue(path, soundNode.remap(value, 0, 127, this.fCtrlLabel[ctrl][i].min, this.fCtrlLabel[ctrl][i].max));
                if (this.output_handler) {
                    this.output_handler(path, this.getParamValue(path));
                }
            }
        }
    }

    /**
     * PitchWeel
     *
     * @param channel - the MIDI channel (0..15, not used for now)
     * @param value - the MIDI controller value (0..16383)
     */
    pitchWheel(channel, wheel) {
        for (var i = 0; i < this.fPitchwheelLabel.length; i++) {
            var pw = this.fPitchwheelLabel[i];
            this.setParamValue(pw.path, soundNode.remap(wheel, 0, 16383, pw.min, pw.max));
            if (this.output_handler) {
                this.output_handler(pw.path, this.getParamValue(pw.path));
            }
        }
    }

    /**
     * Generic MIDI message handler.
     */
    midiMessage(data) {
        var cmd = data[0] >> 4;
        var channel = data[0] & 0xf;
        var data1 = data[1];
        var data2 = data[2];

        if (channel === 9) {
            return;
        } else if (cmd === 11) {
            this.ctrlChange(channel, data1, data2);
        } else if (cmd === 14) {
            this.pitchWheel(channel, (data2 * 128.0 + data1));
        }
    }

    // For WAP
    onMidi(data) {
        midiMessage(data);
    }

    /**
     * @returns {Object} describes the path for each available param and its current value
     */
    async getState() {
        var params = new Object();
        for (let i = 0; i < this.getParams().length; i++) {
            Object.assign(params, { [this.getParams()[i]]: `${this.getParam(this.getParams()[i])}` });
        }
        return new Promise(resolve => { resolve(params) });
    }

    /**
     * Sets each params with the value indicated in the state object
     * @param {Object} state 
     */
    async setState(state) {
        return new Promise(resolve => {
            for (const param in state) {
                if (state.hasOwnProperty(param)) this.setParam(param, state[param]);
            }
            try {
                this.gui.setAttribute('state', JSON.stringify(state));
            } catch (error) {
                console.warn("Plugin without gui or GUI not defined", error);
            }
            resolve(state);
        })
    }

    /**
     * A different call closer to the preset management
     * @param {Object} patch to assign as a preset to the node
     */
    setPatch(patch) {
        this.setState(this.presets[patch])
    }

    static remap(v, mn0, mx0, mn1, mx1) {
        return (1.0 * (v - mn0) / (mx0 - mn0)) * (mx1 - mn1) + mn1;
    }

}

// Factory class
class sound {

    static fWorkletProcessors;

    /**
     * Factory constructor.
     *
     * @param context - the audio context
     * @param baseURL - the baseURL of the plugin folder
     */
    constructor(context, baseURL = "") {
        console.log("baseLatency " + context.baseLatency);
        console.log("outputLatency " + context.outputLatency);
        console.log("sampleRate " + context.sampleRate);

        this.context = context;
        this.baseURL = baseURL;
        this.pathTable = [];

        this.fWorkletProcessors = this.fWorkletProcessors || [];
    }

    heap2Str(buf) {
        let str = "";
        let i = 0;
        while (buf[i] !== 0) {
            str += String.fromCharCode(buf[i++]);
        }
        return str;
    }

    /**
     * Load additionnal resources to prepare the custom AudioWorkletNode. Returns a promise to be used with the created node.
     */
    async load() {
        try {
            const importObject = {
                env: {
                    memoryBase: 0,
                    tableBase: 0,
                    _abs: Math.abs,

                    // Float version
                    _acosf: Math.acos,
                    _asinf: Math.asin,
                    _atanf: Math.atan,
                    _atan2f: Math.atan2,
                    _ceilf: Math.ceil,
                    _cosf: Math.cos,
                    _expf: Math.exp,
                    _floorf: Math.floor,
                    _fmodf: (x, y) => x % y,
                    _logf: Math.log,
                    _log10f: Math.log10,
                    _max_f: Math.max,
                    _min_f: Math.min,
                    _remainderf: (x, y) => x - Math.round(x / y) * y,
                    _powf: Math.pow,
                    _roundf: Math.fround,
                    _sinf: Math.sin,
                    _sqrtf: Math.sqrt,
                    _tanf: Math.tan,
                    _acoshf: Math.acosh,
                    _asinhf: Math.asinh,
                    _atanhf: Math.atanh,
                    _coshf: Math.cosh,
                    _sinhf: Math.sinh,
                    _tanhf: Math.tanh,
                    _isnanf: Number.isNaN,
                    _isinff: function (x) { return !isFinite(x); },
                    _copysignf: function (x, y) { return Math.sign(x) === Math.sign(y) ? x : -x; },

                    // Double version
                    _acos: Math.acos,
                    _asin: Math.asin,
                    _atan: Math.atan,
                    _atan2: Math.atan2,
                    _ceil: Math.ceil,
                    _cos: Math.cos,
                    _exp: Math.exp,
                    _floor: Math.floor,
                    _fmod: (x, y) => x % y,
                    _log: Math.log,
                    _log10: Math.log10,
                    _max_: Math.max,
                    _min_: Math.min,
                    _remainder: (x, y) => x - Math.round(x / y) * y,
                    _pow: Math.pow,
                    _round: Math.fround,
                    _sin: Math.sin,
                    _sqrt: Math.sqrt,
                    _tan: Math.tan,
                    _acosh: Math.acosh,
                    _asinh: Math.asinh,
                    _atanh: Math.atanh,
                    _cosh: Math.cosh,
                    _sinh: Math.sinh,
                    _tanh: Math.tanh,
                    _isnan: Number.isNaN,
                    _isinf: function (x) { return !isFinite(x); },
                    _copysign: function (x, y) { return Math.sign(x) === Math.sign(y) ? x : -x; },

                    table: new WebAssembly.Table({ initial: 0, element: "anyfunc" })
                }
            };

            let real_url = (this.baseURL === "") ? "sound.wasm" : (this.baseURL + "/sound.wasm");
            const dspFile = await fetch(real_url);
            const dspBuffer = await dspFile.arrayBuffer();
            const dspModule = await WebAssembly.compile(dspBuffer);
            const dspInstance = await WebAssembly.instantiate(dspModule, importObject);

            let HEAPU8 = new Uint8Array(dspInstance.exports.memory.buffer);
            let json = this.heap2Str(HEAPU8);
            let json_object = JSON.parse(json);
            let options = { wasm_module: dspModule, json: json };

            if (this.fWorkletProcessors.indexOf(name) === -1) {
                try {
                    let re = /JSON_STR/g;
                    let soundProcessorString1 = soundProcessorString.replace(re, json);
                    let real_url = window.URL.createObjectURL(new Blob([soundProcessorString1], { type: 'text/javascript' }));
                    await this.context.audioWorklet.addModule(real_url);
                    // Keep the DSP name
                    console.log("Keep the DSP name");
                    this.fWorkletProcessors.push(name);
                } catch (e) {
                    console.error(e);
                    console.error("Faust " + this.name + " cannot be loaded or compiled");
                    return null;
                }
            }
            this.node = new soundNode(this.context, this.baseURL,
                {
                    numberOfInputs: (parseInt(json_object.inputs) > 0) ? 1 : 0,
                    numberOfOutputs: (parseInt(json_object.outputs) > 0) ? 1 : 0,
                    channelCount: Math.max(1, parseInt(json_object.inputs)),
                    outputChannelCount: [parseInt(json_object.outputs)],
                    channelCountMode: "explicit",
                    channelInterpretation: "speakers",
                    processorOptions: options
                });
            this.node.onprocessorerror = () => { console.log('An error from sound-processor was detected.'); }
            return (this.node);
        } catch (e) {
            console.error(e);
            console.error("Faust " + this.name + " cannot be loaded or compiled");
            return null;
        }
    }

    async loadGui() {
        return new Promise((resolve, reject) => {
            try {
                // DO THIS ONLY ONCE. If another instance has already been added, do not add the html file again
                let real_url = (this.baseURL === "") ? "main.html" : (this.baseURL + "/main.html");
                if (!this.linkExists(real_url)) {
                    // LINK DOES NOT EXIST, let's add it to the document
                    var link = document.createElement('link');
                    link.rel = 'import';
                    link.href = real_url;
                    document.head.appendChild(link);
                    link.onload = (e) => {
                        // the file has been loaded, instanciate GUI
                        // and get back the HTML elem
                        // HERE WE COULD REMOVE THE HARD CODED NAME
                        var element = createsoundGUI(this.node);
                        resolve(element);
                    }
                } else {
                    // LINK EXIST, WE AT LEAST CREATED ONE INSTANCE PREVIOUSLY
                    // so we can create another instance
                    var element = createsoundGUI(this.node);
                    resolve(element);
                }
            } catch (e) {
                console.log(e);
                reject(e);
            }
        });
    };

    linkExists(url) {
        return document.querySelectorAll(`link[href="${url}"]`).length > 0;
    }
}

// Template string for AudioWorkletProcessor

let soundProcessorString = `

    'use strict';

    // Monophonic Faust DSP
    class soundProcessor extends AudioWorkletProcessor {
        
        // JSON parsing functions
        static parse_ui(ui, obj, callback)
        {
            for (var i = 0; i < ui.length; i++) {
                soundProcessor.parse_group(ui[i], obj, callback);
            }
        }
        
        static parse_group(group, obj, callback)
        {
            if (group.items) {
                soundProcessor.parse_items(group.items, obj, callback);
            }
        }
        
        static parse_items(items, obj, callback)
        {
            for (var i = 0; i < items.length; i++) {
                callback(items[i], obj, callback);
            }
        }
        
        static parse_item1(item, obj, callback)
        {
            if (item.type === "vgroup"
                || item.type === "hgroup"
                || item.type === "tgroup") {
                soundProcessor.parse_items(item.items, obj, callback);
            } else if (item.type === "hbargraph"
                       || item.type === "vbargraph") {
                // Nothing
            } else if (item.type === "vslider"
                       || item.type === "hslider"
                       || item.type === "button"
                       || item.type === "checkbox"
                       || item.type === "nentry") {
                obj.push({ name: item.address,
                         defaultValue: item.init,
                         minValue: item.min,
                         maxValue: item.max });
            }
        }
        
        static parse_item2(item, obj, callback)
        {
            if (item.type === "vgroup"
                || item.type === "hgroup"
                || item.type === "tgroup") {
                soundProcessor.parse_items(item.items, obj, callback);
            } else if (item.type === "hbargraph"
                       || item.type === "vbargraph") {
                // Keep bargraph adresses
                obj.outputs_items.push(item.address);
                obj.pathTable[item.address] = parseInt(item.index);
            } else if (item.type === "vslider"
                       || item.type === "hslider"
                       || item.type === "button"
                       || item.type === "checkbox"
                       || item.type === "nentry") {
                // Keep inputs adresses
                obj.inputs_items.push(item.address);
                obj.pathTable[item.address] = parseInt(item.index);
            }
        }
     
        static get parameterDescriptors() 
        {
            // Analyse JSON to generate AudioParam parameters
            var params = [];
            soundProcessor.parse_ui(JSON.parse(\`JSON_STR\`).ui, params, soundProcessor.parse_item1);
            return params;
        }
       
        constructor(options)
        {
            super(options);
            this.running = true;
            
            const importObject = {
                    env: {
                        memoryBase: 0,
                        tableBase: 0,

                        // Integer version
                        _abs: Math.abs,

                        // Float version
                        _acosf: Math.acos,
                        _asinf: Math.asin,
                        _atanf: Math.atan,
                        _atan2f: Math.atan2,
                        _ceilf: Math.ceil,
                        _cosf: Math.cos,
                        _expf: Math.exp,
                        _floorf: Math.floor,
                        _fmodf: function(x, y) { return x % y; },
                        _logf: Math.log,
                        _log10f: Math.log10,
                        _max_f: Math.max,
                        _min_f: Math.min,
                        _remainderf: function(x, y) { return x - Math.round(x/y) * y; },
                        _powf: Math.pow,
                        _roundf: Math.fround,
                        _sinf: Math.sin,
                        _sqrtf: Math.sqrt,
                        _tanf: Math.tan,
                        _acoshf: Math.acosh,
                        _asinhf: Math.asinh,
                        _atanhf: Math.atanh,
                        _coshf: Math.cosh,
                        _sinhf: Math.sinh,
                        _tanhf: Math.tanh,

                        // Double version
                        _acos: Math.acos,
                        _asin: Math.asin,
                        _atan: Math.atan,
                        _atan2: Math.atan2,
                        _ceil: Math.ceil,
                        _cos: Math.cos,
                        _exp: Math.exp,
                        _floor: Math.floor,
                        _fmod: function(x, y) { return x % y; },
                        _log: Math.log,
                        _log10: Math.log10,
                        _max_: Math.max,
                        _min_: Math.min,
                        _remainder:function(x, y) { return x - Math.round(x/y) * y; },
                        _pow: Math.pow,
                        _round: Math.fround,
                        _sin: Math.sin,
                        _sqrt: Math.sqrt,
                        _tan: Math.tan,
                        _acosh: Math.acosh,
                        _asinh: Math.asinh,
                        _atanh: Math.atanh,
                        _cosh: Math.cosh,
                        _sinh: Math.sinh,
                        _tanh: Math.tanh,

                        table: new WebAssembly.Table({ initial: 0, element: 'anyfunc' })
                    }
            };
            
            this.sound_instance = new WebAssembly.Instance(options.processorOptions.wasm_module, importObject);
            this.json_object = JSON.parse(options.processorOptions.json);
         
            this.output_handler = function(path, value) { this.port.postMessage({ path: path, value: value }); };
            
            this.ins = null;
            this.outs = null;

            this.dspInChannnels = [];
            this.dspOutChannnels = [];

            this.numIn = parseInt(this.json_object.inputs);
            this.numOut = parseInt(this.json_object.outputs);

            // Memory allocator
            this.ptr_size = 4;
            this.sample_size = 4;
            this.integer_size = 4;
            
            this.factory = this.sound_instance.exports;
            this.HEAP = this.sound_instance.exports.memory.buffer;
            this.HEAP32 = new Int32Array(this.HEAP);
            this.HEAPF32 = new Float32Array(this.HEAP);

            // Warning: keeps a ref on HEAP in Chrome and prevent proper GC
            //console.log(this.HEAP);
            //console.log(this.HEAP32);
            //console.log(this.HEAPF32);

            // bargraph
            this.outputs_timer = 5;
            this.outputs_items = [];

            // input items
            this.inputs_items = [];
        
            // Start of HEAP index

            // DSP is placed first with index 0. Audio buffer start at the end of DSP.
            this.audio_heap_ptr = parseInt(this.json_object.size);

            // Setup pointers offset
            this.audio_heap_ptr_inputs = this.audio_heap_ptr;
            this.audio_heap_ptr_outputs = this.audio_heap_ptr_inputs + (this.numIn * this.ptr_size);

            // Setup buffer offset
            this.audio_heap_inputs = this.audio_heap_ptr_outputs + (this.numOut * this.ptr_size);
            this.audio_heap_outputs = this.audio_heap_inputs + (this.numIn * NUM_FRAMES * this.sample_size);
            
            // Start of DSP memory : DSP is placed first with index 0
            this.dsp = 0;

            this.pathTable = [];
         
            // Send output values to the AudioNode
            this.update_outputs = function ()
            {
                if (this.outputs_items.length > 0 && this.output_handler && this.outputs_timer-- === 0) {
                    this.outputs_timer = 5;
                    for (var i = 0; i < this.outputs_items.length; i++) {
                        this.output_handler(this.outputs_items[i], this.HEAPF32[this.pathTable[this.outputs_items[i]] >> 2]);
                    }
                }
            }
            
            this.initAux = function ()
            {
                var i;
                
                if (this.numIn > 0) {
                    this.ins = this.audio_heap_ptr_inputs;
                    for (i = 0; i < this.numIn; i++) {
                        this.HEAP32[(this.ins >> 2) + i] = this.audio_heap_inputs + ((NUM_FRAMES * this.sample_size) * i);
                    }
                    
                    // Prepare Ins buffer tables
                    var dspInChans = this.HEAP32.subarray(this.ins >> 2, (this.ins + this.numIn * this.ptr_size) >> 2);
                    for (i = 0; i < this.numIn; i++) {
                        this.dspInChannnels[i] = this.HEAPF32.subarray(dspInChans[i] >> 2, (dspInChans[i] + NUM_FRAMES * this.sample_size) >> 2);
                    }
                }
                
                if (this.numOut > 0) {
                    this.outs = this.audio_heap_ptr_outputs;
                    for (i = 0; i < this.numOut; i++) {
                        this.HEAP32[(this.outs >> 2) + i] = this.audio_heap_outputs + ((NUM_FRAMES * this.sample_size) * i);
                    }
                    
                    // Prepare Out buffer tables
                    var dspOutChans = this.HEAP32.subarray(this.outs >> 2, (this.outs + this.numOut * this.ptr_size) >> 2);
                    for (i = 0; i < this.numOut; i++) {
                        this.dspOutChannnels[i] = this.HEAPF32.subarray(dspOutChans[i] >> 2, (dspOutChans[i] + NUM_FRAMES * this.sample_size) >> 2);
                    }
                }
                
                // Parse UI
                soundProcessor.parse_ui(this.json_object.ui, this, soundProcessor.parse_item2);
                
                // Init DSP
                this.factory.init(this.dsp, sampleRate); // 'sampleRate' is defined in AudioWorkletGlobalScope  
            }

            this.setParamValue = function (path, val)
            {
                this.HEAPF32[this.pathTable[path] >> 2] = val;
            }

            this.getParamValue = function (path)
            {
                return this.HEAPF32[this.pathTable[path] >> 2];
            }

            // Init resulting DSP
            this.initAux();
        }
        
        process(inputs, outputs, parameters) 
        {
            var input = inputs[0];
            var output = outputs[0];
            
            // Check inputs
            if (this.numIn > 0 && (!input || !input[0] || input[0].length === 0)) {
                //console.log("Process input error");
                return true;
            }
            // Check outputs
            if (this.numOut > 0 && (!output || !output[0] || output[0].length === 0)) {
                //console.log("Process output error");
                return true;
            }
            
            // Copy inputs
            if (input !== undefined) {
                for (var chan = 0; chan < Math.min(this.numIn, input.length); ++chan) {
                    var dspInput = this.dspInChannnels[chan];
                    dspInput.set(input[chan]);
                }
            }
            
            /*
            TODO: sample accurate control change is not yet handled
            When no automation occurs, params[i][1] has a length of 1,
            otherwise params[i][1] has a length of NUM_FRAMES with possible control change each sample
            */
            
            // Update controls
            for (const path in parameters) {
                const paramArray = parameters[path];
                this.setParamValue(path, paramArray[0]);
            }
        
          	// Compute
            try {
                this.factory.compute(this.dsp, NUM_FRAMES, this.ins, this.outs);
            } catch(e) {
                console.log("ERROR in compute (" + e + ")");
            }
            
            // Update bargraph
            this.update_outputs();
            
            // Copy outputs
            if (output !== undefined) {
                for (var chan = 0; chan < Math.min(this.numOut, output.length); ++chan) {
                    var dspOutput = this.dspOutChannnels[chan];
                    output[chan].set(dspOutput);
                }
            }
            
            return this.running;
    	}
        
        handleMessage(event)
        {
            var msg = event.data;
            switch (msg.type) {
                case "destroy": this.running = false; break;
            }
        }
    }

    // Globals
    const NUM_FRAMES = 128;
    try {
        registerProcessor('sound', soundProcessor);
    } catch (error) {
        console.warn(error);
    }
`;

const dspName = "sound";

// WAP factory or npm package module
if (typeof module === "undefined") {
    window.sound = sound;
    window.Faustsound = sound;
    window[dspName] = sound;
} else {
    module.exports = { sound };
}
